version: '3'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: joguinho
    ports:
      - 5432:5432
    expose:
      - 5432

  joguinhoserver:
    build: build/docker/.
    ports:
      - 8080:8080
    depends_on:
      - postgres
